// <auto-generated />
using BackEnd.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231026084931_AddCouponTable")]
    partial class AddCouponTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<double>("MinAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("coupons");

                    b.HasData(
                        new
                        {
                            Id = "7b773500-f4a2-4737-b14c-d909a4c71b10",
                            Code = "10OFF",
                            Discount = 10000.0,
                            MinAmount = 20000.0
                        },
                        new
                        {
                            Id = "cbd2971c-ce9a-47b4-a3f0-e0dd319885ba",
                            Code = "20OFF",
                            Discount = 20000.0,
                            MinAmount = 40000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
